export const ADD_JOB_HISTORY = "ADD_JOB_HISTORY";
export const GET_JOB_HISTORY = "GET_JOB_HISTORY";
export const EDIT_JOB_HISTORY = "EDIT_JOB_HISTORY";
export const JOB_HISTORY_LIST = "JOB_HISTORY_LIST";
