export const LIST_JOB_ADVERTISEMENT = "LIST_JOB_ADVERTISEMENT";
export const ADD_JOB_ADVERTISEMENT = "ADD_JOB_ADVERTISEMENT";
export const DELETE_JOB_ADVERTISEMENT = "DELETE_JOB_ADVERTISEMENT";
export const EDIT_JOB_ADVERTISEMENT = "EDIT_JOB_ADVERTISEMENT";