apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
    {{- template "labels" . }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    
  type: LoadBalancer