#  server.port=9090
#    spring.datasource.url = jdbc:mysql://localhost/almunics545?useSSL=false&serverTimezone=America/Chicago
#    spring.datasource.username = root
#    spring.datasource.password = database
#    spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
#    spring.jpa.hibernate.ddl-auto = update
#    spring.jpa.show-sql=true
#    spring.jpa.hibernate.use-new-id-generator-mappings=false
#    spring.mvc.view.prefix=/WEB-INF/view/
#    spring.mvc.view.suffix=.jsp




#server:
#  port:9090
#
#
#
#spring:
#  datasource:
#    url:jdbc:mysql://localhost/almunics545?useSSL=false&serverTimezone=America/Chicago
#    username:root
#    password:database
#
#  jpa:
#    show-sql: true
#
#
#
#    properties:
#      hibernate:
#        dialect:org.hibernate.dialect.MySQL5Dialect
#        ddl-auto: update
#        use-new-id-generator-mappings:false
#  h2:
#    console:
#      enabled:true
#
#keycloak:
#   realm: Almuni
#   auth-server-url:http://localhost:8180/auth
#   resource:springboot-keycloak
#   public-client:true
#   bearer-only:true
#   kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk
# spring.main.allow-bean-definition-overriding=true
#spring:allow-bean-definition-overriding=true
# server:
#  port: 9090
# spring:
#  main:
#    allow-bean-definition-overriding: true
# application:
#   name: alumni-portal
# datasource:
#   password: database
#   driver-class-name: com.mysql.jdbc.Driver
#
#   # driverClassName: com.mysql.cj.jdbc.Driver
#   url: jdbc:mysql://localhost:3306/alumni-portal
##       jdbc:mysql://localhost/almunics545?useSSL=false&serverTimezone=America/Chicago
##       jdbc:postgresql://localhost:5433/alumni-portal
#   username: root
# jpa:
#   hibernate:
#     ddl-auto: create-drop
#   properties:
#     hibernate:
#       dialect: org.hibernate.dialect.PostgreSQL94Dialect
#       format_sql: true
#   show-sql: false
#   defer-datasource-initialization: true
# sql:
#   init:
#     mode: always
#
